### PR TITLE
Licensing and CSS changes

### PR DESCRIPTION
**Pull request by shrapnelnet**
Just a small PR. i've minified and linked new CSS files to the head of home.php.

I have also added a GPLV3 license to the root of the repository (all software should be licensed bla bla you've heard it before)

i also removed the height property from .main-container. i personally think it looks much better but this is up to your discretion.

i've also deindented the base.css file and made indents consistent throughout.

### CODE REVIEW

**Comment by superswan** [comment]
Awesome. I have one more massive commit to push (sorry) and then I will try to pull this in. 

>I have also added a GPLV3 license to the root of the repository (all software should be licensed bla bla you've heard it before)

Yes, a license should be added. I have yet to determine which license would be best.

**Comment by shrapnelnet** [comment]
sounds great! [choosealicense](https://choosealicense.com/) is a great tool for this if you're not sure, if you didn't already know about it.

what's planned for the next commit? i'd love to add some unfinished features but i don't want to step on your toes.

**Comment by superswan** [comment]
>what's planned for the next commit? i'd love to add some unfinished features but i don't want to step on your toes.

just made the commit. i moved commonly used components into their own code blocks. added comment reply feature, blog categories, and some minor bug fixes.

**Comment by superswan** [comment]
Ok, so I decided to cherry-pick and only push the indentation fix and the minified CSS assets. 

While testing I found the minified CSS assets have caused a regression on the home page. The navbar is no longer centered. (100% my fault since you were working on an older branch and I was making monolithic commits which is bad practice) 

I actually agree the larger header size is pretty ugly but it's accurate to early versions of Myspace. I think this should be something like a configuration or toggle option in the future, something like `header size: classic/modern` 

I will try to select a license soon (It's a little hairy considering copyright stuff)

**Comment by superswan** [comment]
decided to just merge PR

**Pull request merged**
